### ISSUE TITLE
Can't build the package

### ISSUE THREAD

**Issue by akhilesharora** [blevesearch/bleve-explorer#15] opened 2019-07-31 14:46 UTC
build fails on 2 dependencies 
```
# github.com/couchbase/moss
../../../../pkg/mod/github.com/couchbase/moss@v0.0.0-20190322010551-a0cae174c498/api.go:176:15: undefined: ghistogram.Histograms
../../../../pkg/mod/github.com/couchbase/moss@v0.0.0-20190322010551-a0cae174c498/collection.go:98:13: undefined: ghistogram.Histograms
# github.com/blevesearch/bleve-mapping-ui
../../../../pkg/mod/github.com/blevesearch/bleve-mapping-ui@v0.1.0/mapping.go:105:13: undefined: bleve.IndexMapping
```

**Comment by mschoch** [comment] 2019-07-31 14:50
Please show how you are trying to build bleve.

Go modules and dep are not supported, and seem to break every time we make a release.

**Comment by akhilesharora** [comment] 2019-08-02 08:13
I am just building it as per instructions mentioned in the Readme.
```
go build -tags full
```

**Comment by mschoch** [comment] 2019-08-02 12:34
Can you point me to which README you're looking at?  I don't see it in the main bleve README.md.

The `-tags full` was used in the past to pull in some cgo dependencies, but I honestly haven't used that in quite a while.

**Comment by claudius108** [comment] 2020-05-14 18:43
Hi,

I want to build the latest package with go 1.14 in ubuntu 18, and got the following error:
`package github.com/blevesearch/zap/v11: cannot find package "github.com/blevesearch/zap/v11" in any of:
	/usr/local/go/src/github.com/blevesearch/zap/v11 (from $GOROOT)
	/home/claudius/workspace/repositories/go/src/github.com/blevesearch/zap/v11 (from $GOPATH)
`
To build I use `go build`.
Any ideas?

Thanks,
Claudius

P. S. Bleve is very nice, and works fine. Now I want to make an app a single package with website and bleve inside a docker container.

**Comment by mschoch** [comment] 2020-05-14 18:47
@claudius108 bleve no longer supports traditional GOPATH style builds, please see this issue for more details: https://github.com/blevesearch/bleve/issues/1350

**Comment by mschoch** [comment] 2020-05-14 18:54
I should add, we plan to add a go.mod to this project so it works out of the box, we just haven't gotten around to it yet.  I would suggest trying `go mod init github.com/blevesearch/bleve-explorer` and then `go build`.  That would be my next step.

**Comment by claudius108** [comment] 2020-05-14 19:48
Works, thanks a lot!

**Comment by speedplane** [comment] 2020-05-17 21:10
Hi, I'm trying to install `ponzu` which uses this library, and I get the following error:

```
>go get -u github.com/ponzu-cms/ponzu/...
package github.com/blevesearch/zap/v11: cannot find package "github.com/blevesearch/zap/v11" in any of:
        c:\go\src\github.com\blevesearch\zap\v11 (from $GOROOT)
        C:\Users\speedplane\Documents\Projects\Go\src\github.com\blevesearch\zap\v11 (from $GOPATH)
```
Here is the verbose output:
```
>go get -u -v github.com/ponzu-cms/ponzu/...
github.com/ponzu-cms/ponzu (download)
github.com/gorilla/schema (download)
github.com/boltdb/bolt (download)
github.com/gofrs/uuid (download)
github.com/nilslice/jwt (download)
github.com/blevesearch/bleve (download)
github.com/RoaringBitmap/roaring (download)
github.com/glycerine/go-unsnap-stream (download)
github.com/golang/snappy (download)
github.com/tinylib/msgp (download)
github.com/philhofer/fwd (download)
github.com/couchbase/vellum (download)
github.com/blevesearch/mmap-go (download)
get "golang.org/x/sys/windows": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/windows?go-get=1
get "golang.org/x/sys/windows": verifying non-authoritative meta tag
golang.org/x/sys (download)
github.com/blevesearch/zap (download)
package github.com/blevesearch/zap/v11: cannot find package "github.com/blevesearch/zap/v11" in any of:
        c:\go\src\github.com\blevesearch\zap\v11 (from $GOROOT)
        C:\Users\speedplane\Documents\Projects\Go\src\github.com\blevesearch\zap\v11 (from $GOPATH)
get "go.etcd.io/bbolt": found meta tag get.metaImport{Prefix:"go.etcd.io/bbolt", VCS:"git", RepoRoot:"https://github.com/etcd-io/bbolt"} at //go.etcd.io/bbolt?go-get=1
go.etcd.io/bbolt (download)
github.com/steveyen/gtreap (download)
[ABRIDGED]
```

Then, based on @mschoch comment's above, I tried the following:
```
>go mod init github.com/blevesearch/bleve-explorer
go: creating new go.mod: module github.com/blevesearch/bleve-explorer
```
Then, when I retried installing, I got a different error:
```
>go get -u github.com/ponzu-cms/ponzu/...
$GOPATH/go.mod exists but should not
```

Some version info:
```
>go version
go version go1.14.3 windows/amd64
```

**Comment by mschoch** [comment] 2020-05-18 19:48
@speedplane you should open an issue with ponzu.  The command `go mod init github.com/blevesearch/bleve-explorer` was specific (and sufficient) to making `bleve-explorer` build using go modules. For some projects it may not be as simple to convert, the authors of ponzu will have to help you with more specific information.

**Comment by hubyhuby** [comment] 2020-06-28 06:54
Worked for me doing on a simple onfile main.go project
go mod init github.com/blevesearch/bleve-explorer

**Comment by claudius108** [comment] 2020-06-30 09:36
For me, too, thanks.

**Comment by TechplexEngineer** [comment] 2021-01-24 01:05
I'm on `Ubuntu 18.04 / 5.4.0-59-generic` with `go version go1.15.6 linux/amd64` and with a fresh clone there seems to be a problem with exported var name bleve being exported twice

```bash
git clone git@github.com:blevesearch/bleve-explorer.git
cd bleve-explorer
go mod init github.com/blevesearch/bleve-explorer
go build
./bleve-explorer

2021/01/23 20:03:33 Reuse of exported var name: bleve
panic: Reuse of exported var name: bleve


goroutine 1 [running]:
log.Panicln(0xc0001bbe38, 0x2, 0x2)
	/home/techplex/.local/local/go/src/log/log.go:365 +0xae
expvar.Publish(0xd1dbad, 0x5, 0xde3580, 0xc0000487e0)
	/home/techplex/.local/local/go/src/expvar/expvar.go:278 +0x274
expvar.NewMap(0xd1dbad, 0x5, 0x44736a)
	/home/techplex/.local/local/go/src/expvar/expvar.go:310 +0x6e
github.com/blevesearch/bleve/v2.init()
	/home/techplex/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.0.0/config.go:30 +0x3a
```

**Comment by mschoch** [comment] 2021-01-24 01:49
So the problem is that bleve-explorer has not (yet) been updated for bleve v2.  However, it uses bleve-mapping-ui, which has been updated for (and depends on) bleve v2.  This means that bleve-explorer imports bleve v1 and bleve v2.  And both of those packages attempt to register an expvar for `bleve`.

There are 2 fixes (I think).  We can update bleve-explorer to work with bleve-v2.  Or, in theory if you force bleve-explorer to use an old version of bleve-mapping-ui (prior to it switching to bleve v2), it should still work here.

I think we possibly already made a mistake by not making the update to bleve-mapping-ui a major version change, but I could be wrong.  Any thoughts on fixing this @abhinavdangeti ?

**Comment by mschoch** [comment] 2021-01-24 02:43
I started a PR to use bleve v2 here: https://github.com/blevesearch/bleve-explorer/pull/18

Probably should add go.mod/go.sum and make it v2?

**Comment by abhinavdangeti** [comment] 2021-01-25 16:34
> There are 2 fixes (I think). We can update bleve-explorer to work with bleve-v2. Or, in theory if you force bleve-explorer to use an old version of bleve-mapping-ui (prior to it switching to bleve v2), it should still work here.

Right, we'll need a go.mod to use an older version of bleve-mapping-ui.

> I think we possibly already made a mistake by not making the update to bleve-mapping-ui a major version change, but I could be wrong. Any thoughts on fixing this @abhinavdangeti ?

Hmm, not sure if err-ed here. Adding a go.mod to set bleve-mapping-ui to v0.4.0 and bleve to v2.0.1 should address this?

**Comment by mschoch** [comment] 2021-01-25 16:47
OK, so there are multiple paths were discussing here, and it can be confusing.

We can try to make bleve-explorer work with bleve v1, or we can upgrade it to v2, or we can do both, and have a v1 and v2 version of bleve-explorer.

Regarding just adding a go.mod to go back to an older bleve-mapping-ui.  I don't think that will work, because you release bleve-mapping-ui v0.4.0.  Since you did not change the major version number, Go will consider it a drop-in replacement for previous versions (and it may be from an API perspective, but since it changes the dependencies, which have init functions, which have side-effects, it obviously is a breaking change, since this program broke)

**Comment by mschoch** [comment] 2021-01-25 16:58
@TechplexEngineer we have merged the changes upgrade to bleve v2 and providing a working go.mod.  You should no longer experience the panic you reported.  If you have any new problems please open a new issue.  Closing this issue, as we are not aware of any current build issues.

**Closed as completed by mschoch** 2021-01-25 16:58 UTC
