### ISSUE TITLE
getting it running...

### ISSUE THREAD

**Issue by joeblew99** [blevesearch/bleve-explorer#8] opened 2016-02-17 22:40 UTC
Just trying to get this going to play around.
Pulled the code...
Then from read me ran the go build -tags full and boom:::

```
go get -u github.com/blevesearch/bleve-explorer
x-MacBook-Pro:blevesearch apple$ ls
bleve           bleve-explorer      bleve-mapping-ui    go-porterstemmer    segment
x-MacBook-Pro:blevesearch apple$ cd bleve-explorer/
x-MacBook-Pro:bleve-explorer apple$ ls
README.md       bleve-explorer      docs            main.go
bindata_assetfs.go  data            http_util.go        static
x-MacBook-Pro:bleve-explorer apple$ go build -tags full
../bleve/config/config_cznicb.go:15:2: cannot find package "github.com/blevesearch/blevex/cznicb" in any of:
    /usr/local/go/src/github.com/blevesearch/blevex/cznicb (from $GOROOT)
    /Users/apple/workspace/go/src/github.com/blevesearch/blevex/cznicb (from $GOPATH)
../bleve/config/config_cld2.go:15:2: cannot find package "github.com/blevesearch/blevex/detect_lang" in any of:
    /usr/local/go/src/github.com/blevesearch/blevex/detect_lang (from $GOROOT)
    /Users/apple/workspace/go/src/github.com/blevesearch/blevex/detect_lang (from $GOPATH
```

**Comment by mschoch** [comment] 2016-02-17 22:48
If you want to run 'go build' with tags, you also have to run the 'go get' with the same tags, otherwise it won't know to download dependencies pulled in by those tags.

Try:

```
    go get -tags 'full' -u github.com/blevesearch/bleve-explorer
```

That should get you further, though you'll have to have some C deps set up correctly at that point as well.

**Comment by ghost** [comment] 2016-02-26 12:42
thanks @mschoch 

hit an issue:

```
x-MacBook-Pro:blevesearch apple$ go get -tags 'full' -u github.com/blevesearch/bleve-explorer
go: missing Mercurial command. See https://golang.org/s/gogetcmd
package bitbucket.org/tebeka/snowball: exec: "hg": executable file not found in $PATH

```

Its because of come c dependencies it needs i guess ?
I want to cross compile to windows and arm you see.. Any ideas ?

**Comment by ghost** [comment] 2016-02-26 12:46
Ok i grabbed hg.

Now i get:

```
x-MacBook-Pro:blevesearch apple$ go get -tags 'full' -u github.com/blevesearch/bleve-explorer
# github.com/couchbase/goforestdb
../couchbase/goforestdb/commit.go:12:10: fatal error: 'libforestdb/forestdb.h' file not found
#include <libforestdb/forestdb.h>
         ^
1 error generated.
# github.com/blevesearch/blevex/icu
blevex/icu/boundary.go:15:11: fatal error: 'unicode/utypes.h' file not found
 #include "unicode/utypes.h"
          ^
1 error generated.
# github.com/jmhodges/levigo
../jmhodges/levigo/batch.go:4:11: fatal error: 'leveldb/c.h' file not found
 #include "leveldb/c.h"
          ^
1 error generated.
# github.com/tecbot/gorocksdb
../tecbot/gorocksdb/backup.go:4:11: fatal error: 'rocksdb/c.h' file not found
 #include "rocksdb/c.h"
          ^
1 error generated.

```

**Comment by mschoch** [comment] 2016-02-26 13:50
The go wrapper around libstemmer is on bitbucket and requires hg.

The errors you're now getting are because 'full' includes support for all of the C based KV stores.  Some of those options are described here: http://www.blevesearch.com/docs/Building/

You'll need to have ICU, leveldb and rocksdb built locally.  And you'll need to have all of your CGO_ environment variables configured to find the headers and librariries.

**Comment by ghost** [comment] 2016-02-26 15:04
Hey @mschoch 
Ok thats some serious dependencies.
I think i will not continue on getting this going. I was only playing with this so that i can learn more about using Bleve.

For my current project, I  really just need something very similar to what https://github.com/blevesearch/fosdem-search does.
I am using it as a base to learn and then implement that same thing on my data.
However, i found a bug in Fosdem:
https://github.com/blevesearch/fosdem-search/issues/3

**Comment by mschoch** [comment] 2016-02-26 15:06
In that case there is absolutely no reason for you to use any build tags at all.  That is only needed for advanced users.

**Comment by joeblew99** [comment] 2016-02-26 18:51
Ah ? When I tried to compile it with no build tags it failed though.
Any ideas ?

**Comment by mschoch** [comment] 2016-02-26 18:53
Your very first comment has errors when doing build with tags.  If you get errors without build tags, you have to tell us what they are.

**Comment by ghost** [comment] 2016-02-26 18:57
sorry ..

go build
./bleve.explorer starts up

http://localhost:8095/static/
- Gets nothing

in terminal:

```
x-MacBook-Pro:bleve-explorer apple$ ./bleve-explorer 
2016/02/26 19:51:57 Listening on :8095
2016/02/26 19:52:15 http: panic serving [::1]:58965: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc82013c000, 0xc8acb0, 0xc82002c260)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200dd6b0, 0xc820132960, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/apple/workspace/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc8ae30, 0xc82013c630, 0xc8200eeee0, 0xc89888, 0xc8200dd6b0, 0x6882c0, 0x1, 0x756ea171843501)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200e08c0, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc898b0, 0xc8200e08c0, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /Users/apple/workspace/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200e0990, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200dd770, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820015680, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /Users/apple/workspace/go/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(*ServeMux).ServeHTTP(0xc820012900, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c6c0, 0xc8ae30, 0xc82013c630, 0xc8200eeee0)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82013c000)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/02/26 19:52:15 http: panic serving [::1]:58966: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc82013c790, 0xc8acb0, 0xc82002c2b0)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200dd6b0, 0xc820132d20, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/apple/workspace/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc8ae30, 0xc82013c840, 0xc8200eefc0, 0xc89888, 0xc8200dd6b0, 0x6882c0, 0x1, 0x756ea13376d901)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200e08c0, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc898b0, 0xc8200e08c0, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /Users/apple/workspace/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200e0990, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200dd770, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820015680, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /Users/apple/workspace/go/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(*ServeMux).ServeHTTP(0xc820012900, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c6c0, 0xc8ae30, 0xc82013c840, 0xc8200eefc0)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82013c790)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/02/26 19:52:17 http: panic serving [::1]:58967: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc82013c9a0, 0xc8acb0, 0xc82002c2b8)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200dd6b0, 0xc8201330e0, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/apple/workspace/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc8ae30, 0xc82013ca50, 0xc8200ef0a0, 0xc89888, 0xc8200dd6b0, 0x6882c0, 0x1, 0x756ea13b897101)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200e08c0, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc898b0, 0xc8200e08c0, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /Users/apple/workspace/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200e0990, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200dd770, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820015680, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /Users/apple/workspace/go/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(*ServeMux).ServeHTTP(0xc820012900, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c6c0, 0xc8ae30, 0xc82013ca50, 0xc8200ef0a0)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82013c9a0)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/02/26 19:52:20 http: panic serving [::1]:58968: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc82013cbb0, 0xc8acb0, 0xc82002c2c0)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200dd6b0, 0xc8202023a0, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/apple/workspace/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc8ae30, 0xc8202060b0, 0xc820212000, 0xc89888, 0xc8200dd6b0, 0x6882c0, 0x1, 0x756ea1441efd01)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200e08c0, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc898b0, 0xc8200e08c0, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    /Users/apple/workspace/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200e0990, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc8ae30, 0xc8202060b0, 0xc820212000)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200dd770, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820015680, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    /Users/apple/workspace/go/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(*ServeMux).ServeHTTP(0xc820012900, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c6c0, 0xc8ae30, 0xc8202060b0, 0xc820212000)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82013cbb0)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2016/02/26 19:52:20 http: panic serving [::1]:58969: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc820206210, 0xc8acb0, 0xc820242000)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200dd6b0, 0xc820202760, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/apple/workspace/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc8ae30, 0xc8202062c0, 0xc8202120e0, 0xc89888, 0xc8200dd6b0, 0x6882c0, 0x1, 0x756ea119194601)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200e08c0, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc898b0, 0xc8200e08c0, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /Users/apple/workspace/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200e0990, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /usr/local/go/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200dd770, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820015680, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /Users/apple/workspace/go/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.(*ServeMux).ServeHTTP(0xc820012900, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82012c6c0, 0xc8ae30, 0xc8202062c0, 0xc8202120e0)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820206210)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6

```

**Comment by mschoch** [comment] 2016-02-26 18:59
that appears to be duplicate of #6 

I didn't write the assetfs code so I don't know why it's failing.  I may just have to rip that code out.

**Comment by joeblew99** [comment] 2016-02-26 19:07
Bummer. Might be best to toggle it off for now ?

**Comment by mschoch** [comment] 2016-02-26 19:40
We are looking at it now, there were some upstream changes to assetfs.

**Comment by mschoch** [comment] 2016-02-26 20:56
We got a fix from @steveyen and it now works correctly for me with latest code in clean gopath.  Please grab the latest and try again.

**Comment by ghost** [comment] 2016-02-26 21:03
deep get:

go get -u github.com/blevesearch/bleve-explorer/...

yep it works for me too.

thanks for such amazingly quick feedback. Its the weekend here, but will
play around with this on Monday.

**Comment by mschoch** [comment] 2016-02-26 21:09
Sure, no problem.  We left it in a broken state for too long, glad its fixed and working.

**Closed as completed by mschoch** 2016-02-26 21:09 UTC
